- src/view/Layout.js
When a tab is moved the component is rendered either up or down in the DOM. If the component moves down it is re-rendered by react. When the component contains certain elements like iframe and object tag this causes them to reload and lose and state within the tag. The react developers are not planning to fix this behaviour.
This PR ensures that tabs are rendered in a consistent order in the DOM so that when they move in the tree they do not move in the DOM. Tabset components are rendered first so as not to break the rendering, and splitters last.
> Render tab components in consistent order in DOM

- README.md
On linux, file name casing matters. 
The directory in `node_modules` is named `flexlayout-react` with a lowercase `l`, trying to include css styles using `node_modules/flexLayout-react/...` with an uppercase `L` does not work on linux (tested with the parcel bundler)
> Fix case sensitivity of the node_modules path

- README.md
- src/model/Model.ts
- src/view/Layout.tsx
I noticed the CSS transition speed for the tab drag outline was hard-coded at 0.3 seconds. I found this to be a bit slow for my taste. This PR would make it customizable via a global attribute.
Another option would be to move it out of code and into CSS. Both options have pros and cons, but an attribute met my needs well, so I went with that. If you disagree with the approach, I'm happy to discuss.
If you want to rename `tabDragSpeed` to something else, I don't mind. I just care about the functionality.
Thank you!
> Add tabDragSpeed global attribute

- src/DragDrop.ts
The event parameter is undefined when the drag starts, and was causing an error.
> Fix Layout.addTabWithDragAndDrop()

- README.md
- src/view/Layout.tsx
Non-breaking change.
Currently, we halt processing an action if an implementation for onAction has been provided.
We can enhance this by allowing the implementation to optionally return the action, or choose not too.
Therefore the onAction truly does become an interception of the action.
> onAction implementation allows doAction when action returned

- src/model/Model.ts
- src/view/Layout.tsx
Non-breaking change.
Enhance the onModelChange API by including the action as one of the parameters.
Helpful when looking to see why a model change has occurred.
> onModelChange API include action

- src/view/TabSet.tsx
Added onTouchStart to overflowButton in TabSet to prevent default touch gesture on tablets and make the button work.
> Added onTouchStart to overflowButton in TabSet for tablets

- src/view/Layout.tsx
- src/view/Tab.tsx
- src/view/TabSet.tsx
-  Ran the following codemod `npx react-codemod rename-unsafe-lifecycles`to rename all deprecated lifecycles to their new names.
> Removes react unsafe lifecycle warnings

- package.json
- src/view/Layout.tsx
This diff fixes error when library is imported in nodejs. (often happens
with server side rendering and test environments).
fix #115
> Check global variables existence before usage

- src/PopupMenu.tsx
The existing popup placement code uses the document's width and height to place the popups, but they're placed via `position:absolute` to window-relative coordinates. This has two issues:
1. If the document is scrollable, then the popup will appear in the wrong place. I tested that this is indeed the case on the demo by adding a lot of flowed text in the background (a bunch of toolbars), removing `overflow:auto`, scrolling, and then clicking on a popup button:
2. If the document consists entirely of a FlexLayout, as it does in my application, then because it's absolutely positioned, the document has zero height. This leads to very wrong placement of the popup menu (below the bottom of the window).
This PR uses the document's window size, if it's available, and falls back to the old method …
> Use window size to place popup menus

- .npmignore
This simple PR publishes the `src` directory on NPM, or more precisely, removes it from `.npmignore`. This has two main advantages:
1. Those writing their application in TypeScript can use the source code directly instead of the built `lib` code, via `import FlexLayout from "flexlayout-react/src/index"`.
2. If you `npm install` from Github instead of NPM, then you get an actually workable copy of the repository. (`npm install` won't take anything listed in `.npmignore`.) This is useful to me for using not-yet-released-to-NPM versions, as I can easily add TypeScript to my build chain.
There are other things that would make this install-from-Github experience better, like [defining a `prepare` script](https://blog.jim-nielsen.com/2018/installing-and-building-an-npm-package-from-github/#insta …
> Publish src directory

- README.md
- src/view/BorderButton.tsx
- src/view/BorderTabSet.tsx
- src/view/Layout.tsx
- src/view/TabButton.tsx
- src/view/TabSet.tsx
Fix #130 as proposed: implement a general `icons` prop with allowed keys of `close`, `maximize`, `restore`, `more`, and `popout`. (There were other choices for these names used within the code and CSS; I chose to match the filenames in `images` but am happy to change them.)  `closeIcon` is still supported for backward compatibility (its value gets put into `icons.close`); let me know if you'd rather remove that.  (I did remove it from the documentation to encourage the new system.)
The implementations mimic the existing implementation of `closeIcon` in that it adds the specified React node to the `<button>`, but it doesn't actually stop the existing CSS from rendering the old button as a background. This is still really helpful, because it's easy to override the CSS.  But we could explore …
> Custom icon support via icons prop

- README.md
- package.json
- src/I18nLabel.ts
- src/view/BorderButton.tsx
- src/view/TabButton.tsx
Currently, the `customizeTabSet` callback is given an empty `buttons` list to which the user can add custom buttons.  But the analogous `customizeTab` does not; only the close button gets rendered.  This PR unifies the two by passing in a similar `buttons` array to `customizeTab`.  The code is very similar to the `customizeTabSet` case.
This is a little awkward to use because buttons in this context because, in addition to defining an `onClick` helper, the user also needs to define an `onMouseDown` and `onTouchStart` helpers with value `(e) => e.preventDefault()`.  (This took me a while to figure out, but the close button does it, and it's to deal with tab renaming.)  This would probably be good to document somewhere, but I wasn't sure where.
While I was here, I also added a missing …
> Allow customizeTab to add custom buttons to tabs

- style/dark.scss
- style/light.scss
This PR makes a small tweak to the `.scss` files (for those of us including them directly) so that we can override the variables from outside. It shouldn't affect the built `.css` files.
The recent change to `font-size` inspired this PR. Now people can switch back if desired, without having to duplicate the entire `light.scss` or `dark.scss`.
> Use !default in scss to allow overriding specific variables

- README.md
- src/model/Actions.ts
- src/model/BorderNode.ts
- src/model/IDropTarget.ts
- src/model/Model.ts
- src/model/TabSetNode.ts
- style/dark.css
- style/light.css
Fix #137. Summary of changes:
* `Actions.addNode` and `Actions.moveNode` support an additional optional boolean argument `doNotSelect`. This gets passed through to `drop()`.
* If the argument is false, the added or moved node is selected. This is as it was before for TabSets (but see below for BorderNodes)
* If the argument is true, the node isn't selected.
* Breaking change: dropping onto a BorderNode now automatically selects the tab, unless `doNotSelect` is true. The old behavior was to select the tab unless another tab was already selected for that border.  I'd actually encountered this before, and it seems inconsistent and confusing.  Now it's consistent with TabSet.
> Allow adding and moving tabs without selecting them

- src/model/TabSetNode.ts
Example of *current* behavior:
* Consider a TabSet with three tabs, call them 1, 2, 3.
* If you drag tab 2 or 3 out of the TabSet to another location, then FlexLayout currently *always selects tab 1*.
* This leads to some pretty weird behavior. For example:
* If tab 2 is selected, and you drag tab 3 out of the TabSet, then tab 2 *deselects* and tab 1 gets selected! (This is particularly confusing/jarring.)
* If tab 3 is selected, and you drag tab 3 out of the TabSet, then tab 1 gets selected, even though tab 2 is closer. (This isn't a huge deal, but feels counterintuitive.)
This PR implements Chrome's behavior:
* If you drag a tab out of a TabSet or a Border, and it wasn't selected, then nothing changes. (This was already implemented for Border, but not TabSet. In particular, I preserved …
> Select adjacent tab when dragging selected tab out of TabSet/Border

- src/view/BorderTabSet.tsx
- src/view/TabSet.tsx
Buttons in tabs and tabsets and borders need to `stopPropagation` in `onMouseDown` and `onTouchStart`, to avoid the drag behavior of the rest of the header.  But a few buttons were missing this behavior.  For example, the maximize button currently doesn't work on Chrome on Android.  With this fix, the button works.
> Intercept mousedown and touchstart events in all buttons

- README.md
Help fix #197 by showing the use of `Actions` under the typical namespace `FlexLayout.Actions`, and similarly for `DockLocation`.  At the same time, clean up that section of the docs a bit, in particular putting the two examples together and fixing a section heading.
> Document FlexLayout.Actions

- style/dark.scss
- style/gray.scss
- style/light.scss
This PR makes small tweaks to the default styles, achieving the following goals:
1. In dark mode, distinguish border background color from tab color.  (A recent update made them the same, which seems inconsistent and hard to see.)
2. Distinguish selected border tab with a different background color.  (This is new; I think it makes it pop slightly better, but isn't a big deal.)
3. `light.scss` specifies `background-color` if and only if `dark.scss` specifies `background-color`.  This is useful for including both sets of CSS rules, under a custom root class that allows toggling between light and dark mode.  ([Example](https://github.com/edemaine/comingle/blob/master/client/FlexLayout.sass))
Happy to tweak the specific color choices, or discuss whether these are reasonable objectives.
> Tweak border button background colors

- README.md
- src/DragDrop.ts
- src/model/Model.ts
- src/view/Layout.tsx
This PR adds a configuration option `onExternalDrag` to allow the layout to handle drags from outside the layout (e.g. files or links or even draggable objects from other parts of the app outside the layout) that cause the creation of tabs.  In [my app](https://github.com/edemaine/comingle), I want to be able to drag URLs from e.g. another browser window in order to create a tab that iframes that URL.
Most of the changes are local to DragDrop, which has extra event handlers for the many various drag/drop events (and the usual [counter workaround](https://www.smashingmagazine.com/2020/02/html-drag-drop-api-react/) to handle dragging entering/leaving various elements).  The main other change is that Layout needs to listen to `dragenter` as yet another way to start a new drag operation.
I …
> Drag external objects onto layout to make tabs

- src/DragDrop.ts
- src/Rect.ts
- src/view/Layout.tsx
This is an attempt to fix the [issue reported](https://github.com/caplin/FlexLayout/pull/196#issuecomment-813021173) with external drag, that you can't drag over an iframe.  I figured out how to get the glass to work even with pointer events enabled: just needed to listen to some more drag events.  So now the behavior should be:
* You can drag an external link onto the FlexLayout, even over an iframe in the FlexLayout
* You still cannot drag a link from within an iframe onto the page. I believe this is because of  [this security feature](https://bugs.chromium.org/p/chromium/issues/detail?id=59081), so we would need [this Chrome feature request](https://bugs.chromium.org/p/chromium/issues/detail?id=981124), to fix it.
I'm a little unhappy with how, once you start dragging onto the …
> External drag, with pointerEvents enabled

- src/view/Splitter.tsx
I noticed that dragging splitters does not work well when tabs have iframes in them, at least in my app: if you drag so fast that your mouse gets over an iframe, then the drag hangs and FlexLayout gets confused.
It seems that the default glass sizing to match `document.body` does not work well (I guess then there's a difference between `position: absolute` and `position: fixed`).  But specifying the `rootElement` explicitly works well.
This is the last untouched call to `startDrag`, so hopefully the last bug fix.  Sorry for not catching it earlier.
> Fix dragging of splitters

- package.json
- src/model/Model.ts
Fixes an issue introduced with #255 where IDs may conflict when they are saved and later introduced.
Downside: introduces 1 dependency. Upside: anyone with React already has this dependency installed.
@nealus This is the fix for that problem with the tab storage
> Use UUIDs for IDs

- README.md
- src/PopupMenu.tsx
- src/model/TabNode.ts
- src/view/BorderButton.tsx
- src/view/TabButton.tsx
As a developer, I should be able to set the help text for the created tabs to enhance usability. Especially, when a large number of tabs are open in a give `TabSet`.
Provide a configuration option for tabs that can aid a developer to specify the help text to be displayed upon tab hover. This PR aims to expose such an option, `helpText`.
> Option to set the help text for tabs

- src/view/TabButton.tsx
fixed a bug from tabIcon can't show, because (typeof undefined) return a string value 'undefined' is not equal undefined;
typeof undefined === undefined     // false
typeof undefined === "undefined" // true
> fixed a bug from tabIcon can't show

- src/view/TabOverflowHook.tsx
This fixes Chrome warnings about non-passive `wheel` event listener.
<details>
```
[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
(anonymous) @ TabOverflowHook.js:44
commitHookEffectListMount @ react-dom.development.js:22795
commitPassiveMountOnFiber @ react-dom.development.js:24505
commitPassiveMountEffects_complete @ react-dom.development.js:24469
commitPassiveMountEffects_begin @ react-dom.development.js:24456
commitPassiveMountEffects @ react-dom.development.js:24444
flushPassiveEffectsImpl @ react-dom.development.js:26639
flushPassiveEffects @ react-dom.development.js:26592
commitRootImpl @ …
```
> fix chrome warning for wheel event listener

- src/model/Model.ts
- src/view/Layout.tsx
This is similar to #64 , which has been reverted for an unknown reason.
It's a non-breaking change that adds a 2nd `action` argument to `onModelChange` prop function.
It can help the user determine the source of the change, e.g. for filtering out layout changes that are produced by certain action type.
**Example use case:** I'd like to store layout in localStorage after changes, but ignore changes produces by the user switching between tabs and tabsets since they don't alter page layout.
> Added `action` argument to `onModelChange` prop function call

- README.md
Minor documentation fix, swapping the descriptions of the `minHeight` and `minWidth` attributes in the tabset configuration, as they were mismatched.
> Swap descriptions for minHeight and minWidth attributes

- src/model/Model.ts
This new function is part of my solution for [Issue 51](https://github.com/caplin/FlexLayout/issues/51). When it tries to add to the active tab set but there is no active tab set I need to find some tab set to add to instead. Ideally layout.addTabToActiveTabSet() would also be changed to use this as well, but I didn't want to submit an MR that could change functionality without hearing from the developers first.
> Add function to find first tab set of the root node.

- src/DragDrop.ts
- src/view/Layout.tsx
HTMLDocument is deprecated in favor of Document.
> refactor: use Document instead of HTMLDocument

- src/DragDrop.ts
- src/view/BorderButton.tsx
- src/view/TabButton.tsx
keyCode is deprecated. Replaced usages with code instead.
> refactor: use code instead of keyCode for KeyboardEvent

- examples/demo/TabStorage.tsx
- src/PopupMenu.tsx
- src/Rect.ts
- src/view/BorderButton.tsx
- src/view/FloatingWindow.tsx
- src/view/Layout.tsx
- src/view/Splitter.tsx
- src/view/TabButton.tsx
- src/view/TabOverflowHook.tsx
When FlexLayout is unmounted from the page, there is a race condition where some FlexLayout internal code may attempt to access selfRef.current when it is undefined (as the DOM has already been removed from the page).
The TypeScript code was using the ! operator to ignore the potential null values in that field, which results in null-access errors when unmounting the page.
Various other locations where undefined reference errors were seen have also been fixed to handle the respective variables being undefined.
https://github.com/caplin/FlexLayout/issues/352#issuecomment-1769322206
Fixes: #352
> fix: handle undefined references when page is unmounted
